# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeWork-3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeWork-3
  pod 'SnapKit', '~> 5.0.0'

end
